#yuewyriuywueyr

services:

  #mysql service
  mysql:
    #version
    image: mysql:8.0

   #if crash
    restart: always
    
    environment:
      #sets password, makes database, make database user and password
      MSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: musicdb
      MYSQL_USER: appuser
      MYSQL_PASSWORD: password

    ports: 
      #MySQL default port
      - "3306:3306"

    volumes:
      #volume for storage
      - mysql_data:/var/lib/mysql

  backend:
    #use dockerfile from backend
    build: ./backend

    ports:
      #port
      - "5000:5000"

    depends_on:
      #start mysql container first
      - my_sql

    environment:
      #host is mysql, have user and password, uses musicdb
      DB_HOST: mysql
      DB_USER: appuser
      DB_PASSWORD: password
      DB_NAME: musicdb

  frontend:
    #use dockerfile
    build: .

    ports: 
      #ports
      - "3000:5173"

    #build other two first
    depends_on:
      - backend

volumes:
  #makes volume for storage use
  mysql_data:

