services:
  backend:
    build: ./backend

    ports:
      - "5001:5001"

    environment:
      RAILWAY_MYSQL_HOST: ${RAILWAY_MYSQL_HOST}
      RAILWAY_MYSQL_PORT: ${RAILWAY_MYSQL_PORT}
      RAILWAY_MYSQL_USER: ${RAILWAY_MYSQL_USER}
      RAILWAY_MYSQL_PASSWORD: ${RAILWAY_MYSQL_PASSWORD}
      RAILWAY_MYSQL_DATABASE: ${RAILWAY_MYSQL_DATABASE}

  frontend:
    build: .

    ports:
      - "3000:5173"

    depends_on:
      - backend
